### PR TITLE
Update fmutils.go

### PR DESCRIPTION
**Pull request by SachsA**
This condition was missing when trying to filter on nested structs it was panicing.

### CODE REVIEW

**Comment by mennanov** [comment]
Please add a test that covers this case.

**Comment by SachsA** [comment]
Yes of course. Sorry I just realized that I didn't commit them... Forgive me.
I will do it tomorrow.

**Comment by SachsA** [comment]
@mennanov There you go, I added some tests. Hope this is ok for you. Feel free to reach me if you need.

**Comment by mennanov** [comment]
Your pull request actually revealed that the code does not currently support an important use case: masks in repeated non-scalar fields.
I created a pull request to address this issue: https://github.com/mennanov/fmutils/pull/2
It should also fix the problem this pull request addresses.
Please, take a look at that pull request and let me know if it works for you. If everything is OK i'll merge my pull request in favor of this one.

Thanks for contributing!

**Pull request closed without merging**
